### ISSUE TITLE
StatsEngine#metrics usage in tests

### ISSUE THREAD

**Issue by jasonrclark** [yuki24/newrelic-httpclient#1]
Hey there! We noticed that the tests for your gem are using the `StatsEngine#metrics` method, which with version 3.11.0 of `newrelic_rpm` is going away.

Luckily, we've provided a replacement which is what we use internally for validating metric recording called `assert_metrics_recorded`. You can see more documentation for it at https://docs.newrelic.com/docs/agents/ruby-agent/frameworks/third-party-instrumentation#testing-your-extension.

Let us know if you have any problems with updating to use the new testing methods, and thanks for your work extending the Ruby agent! :sparkles:

cc/ @tkrajcar

**Comment by yuki24** [comment]
@jasonrclark Thanks for informing! Do I still have to maintain this repo? It seems like the newrelic_rpm gem already has [support for HTTPClient](https://github.com/newrelic/rpm/blob/fd0ec53558f75079289a88c425f6409df21b4029/lib/new_relic/agent/instrumentation/httpclient.rb) and this gem is no longer needed. I'm totally happy with replacing `StatsEngine#metrics` with `assert_metrics_recorded`, though.

**Comment by jasonrclark** [comment]
D'oh, you're totally right @yuki24! I tried to filter out the various extensions which `newrelic_rpm` has already taken the place of, but somehow mixed up on this one.

Thanks again for your work on it!

**Comment by yuki24** [comment]
@jasonrclark Thanks, I'll deprecate this gem and put an EOL announcement into the README.
